/**
 * Generated by @openapi-codegen
 *
 * @version v1
 */
export type AlbumDto = {
  /**
   * @format uuid
   */
  id: string;
  name: string;
  artists: SimpleArtistDto[];
  type?: AlbumType;
  /**
   * @format int32
   */
  releaseYear: number;
  artworks?: ArtworkDto;
  /**
   * @format date-time
   */
  createdAt: string;
  favorited: boolean;
  tracks: SimpleTrackDto[];
  genres: GenreDto[];
};

export type AlbumRecommendationDto = {
  album: SimpleAlbumDto;
  /**
   * @format int32
   */
  similarityPercentage: number;
  similarityLabel: string;
};

export type AlbumType = "Single" | "EP" | "MiniAlbum" | "Album" | "Compilation";

export type ArtistDto = {
  /**
   * @format uuid
   */
  id: string;
  name: string;
  favorited: boolean;
  releases: SimpleAlbumDto[];
  featuredIn: SimpleAlbumDto[];
  remixerIn: SimpleAlbumDto[];
  inCompilation: SimpleAlbumDto[];
};

export type ArtistRole = "Main" | "Guest" | "Remixer";

export type ArtistWithRoleDto = {
  /**
   * @format uuid
   */
  id: string;
  name: string;
  favorited: boolean;
  role: ArtistRole;
};

export type ArtworkDto = {
  small: string;
  medium: string;
  original: string;
  colors: string[];
};

export type ArtworkSize = "Small" | "Medium" | "Original";

export type AudioFile = {
  /**
   * @format uuid
   */
  id: string;
  /**
   * @format date-time
   */
  createdAt: string;
  /**
   * @format date-time
   */
  updatedAt: string;
  filePath: string;
  /**
   * @format double
   */
  fileSizeInBytes: number;
  /**
   * @format uuid
   */
  audioMetadataId: string;
  audioMetadata: AudioMetadata;
  /**
   * @format uuid
   */
  libraryId: string;
  library: MusicLibrary;
};

export type AudioMetadata = {
  /**
   * @format uuid
   */
  id: string;
  /**
   * @format date-time
   */
  createdAt: string;
  /**
   * @format date-time
   */
  updatedAt: string;
  /**
   * @format int32
   */
  bitrate: number;
  /**
   * @format int32
   */
  bitDepth?: number | null;
  /**
   * @format double
   */
  sampleRate: number;
  /**
   * @format int32
   */
  channels?: number | null;
  codec: string;
};

export type FileWatcherSettings = {
  /**
   * @format int32
   */
  debounceSeconds: number;
};

export type GenreDto = {
  /**
   * @format uuid
   */
  id: string;
  name: string;
};

export type MusicLibrary = {
  /**
   * @format uuid
   */
  id: string;
  /**
   * @format date-time
   */
  createdAt: string;
  /**
   * @format date-time
   */
  updatedAt: string;
  libraryPath: string;
  /**
   * @format date-time
   */
  lastScan: string;
  watchForChanges: boolean;
  audioFiles: AudioFile[];
};

export type MusicLibraryDto = {
  /**
   * @format uuid
   */
  id: string;
  libraryPath: string;
  /**
   * @format date-time
   */
  lastScan: string;
};

export type OutputFormat = "AAC" | "MP3" | "Ogg" | "Opus" | "Remux";

export type PathSettings = {
  data: string;
};

export type PlaylistDto = {
  /**
   * @format uuid
   */
  id: string;
  name: string;
  description: string;
  tracks: PlaylistTrackDto[];
  /**
   * @format date-time
   */
  createdAt: string;
  /**
   * @format date-time
   */
  updatedAt: string;
};

export type PlaylistTrackDto = {
  /**
   * @format uuid
   */
  id: string;
  /**
   * @format int32
   */
  position: number;
  /**
   * @format date-time
   */
  addedAt: string;
  track: SimpleTrackDto;
};

export type ScanInitiatedDto = {
  scans: ScanRequestInfo[];
};

export type ScanJobProgress = {
  /**
   * @format uuid
   */
  requestId: string;
  /**
   * @format uuid
   */
  libraryId: string;
  libraryName: string;
  /**
   * @format int32
   */
  expectedTracks: number;
  /**
   * @format int32
   */
  tracksAdded: number;
  /**
   * @format int32
   */
  tracksUpdated: number;
  /**
   * @format int32
   */
  tracksDeleted: number;
  /**
   * @format int32
   */
  embeddingsCompleted: number;
  /**
   * @format date-time
   */
  startedAt: string;
  /**
   * @format date-time
   */
  completedAt?: string | null;
  isFailed: boolean;
  errorMessage?: string | null;
};

export type ScanRequestInfo = {
  /**
   * @format uuid
   */
  requestId: string;
  /**
   * @format uuid
   */
  libraryId: string;
  libraryName: string;
};

export type SearchResult = {
  artists: SimpleArtistDto[];
  albums: SimpleAlbumDto[];
  tracks: TrackDto[];
};

export type SearchResultPaginatedCustomData = {
  /**
   * @format int32
   */
  availableRecords: number;
  /**
   * @format int32
   */
  totalRecords: number;
  /**
   * @format int32
   */
  resultCount: number;
  data: SearchResult;
};

export type ServerConfiguration = {
  /**
   * @format int32
   */
  configVersion: number;
  paths: PathSettings;
  fileWatcher: FileWatcherSettings;
};

export type SimpleAlbumDto = {
  /**
   * @format uuid
   */
  id: string;
  name: string;
  artists: SimpleArtistDto[];
  type?: AlbumType;
  /**
   * @format int32
   */
  releaseYear: number;
  artworks?: ArtworkDto;
  /**
   * @format date-time
   */
  createdAt: string;
  favorited: boolean;
};

export type SimpleAlbumDtoPaginatedQuery = {
  /**
   * @format int32
   */
  availableRecords: number;
  /**
   * @format int32
   */
  totalRecords: number;
  /**
   * @format int32
   */
  resultCount: number;
  data: SimpleAlbumDto[];
};

export type SimpleArtistDto = {
  /**
   * @format uuid
   */
  id: string;
  name: string;
  favorited: boolean;
};

export type SimpleArtistDtoPaginatedQuery = {
  /**
   * @format int32
   */
  availableRecords: number;
  /**
   * @format int32
   */
  totalRecords: number;
  /**
   * @format int32
   */
  resultCount: number;
  data: SimpleArtistDto[];
};

export type SimpleTrackAlbumDto = {
  /**
   * @format uuid
   */
  id: string;
  name: string;
};

export type SimpleTrackDto = {
  /**
   * @format uuid
   */
  id: string;
  title: string;
  /**
   * @format int32
   */
  durationInSeconds: number;
  /**
   * @format int32
   */
  trackNumber: number;
  /**
   * @format int32
   */
  discNumber: number;
  album: SimpleTrackAlbumDto;
  artists: ArtistWithRoleDto[];
  genre?: GenreDto;
  favorited: boolean;
};

export type StreamDto = {
  link: string;
  transcodeInfo?: TranscodeInfoDto;
  artworkUrl?: string | null;
};

export type TrackDto = {
  /**
   * @format uuid
   */
  id: string;
  title: string;
  /**
   * @format int32
   */
  durationInSeconds: number;
  comment?: string | null;
  /**
   * @format int32
   */
  trackNumber: number;
  /**
   * @format int32
   */
  discNumber: number;
  artists: ArtistWithRoleDto[];
  album: SimpleAlbumDto;
  genre?: GenreDto;
  favorited: boolean;
};

export type TranscodeInfoDto = {
  /**
   * @format uuid
   */
  jobId: string;
  format: OutputFormat;
  /**
   * @format int32
   */
  bitrate: number;
  codec?: string | null;
};
