/**
 * Generated by @openapi-codegen
 *
 * @version v1
 */
export type AlbumDto = {
  /**
   * @format uuid
   */
  id: string;
  name: string;
  artists: SimpleArtistDto[];
  type?: AlbumType;
  /**
   * @format int32
   */
  releaseYear: number;
  artworks: ArtworkDto;
  /**
   * @format date-time
   */
  createdAt: string;
  tracks: SimpleTrackDto[];
  genres: GenreDto[];
};

export type AlbumType = "Single" | "EP" | "MiniAlbum" | "Album" | "Compilation";

export type ArtistDto = {
  /**
   * @format uuid
   */
  id: string;
  name: string;
  releases: SimpleAlbumDto[];
  featuredIn: SimpleAlbumDto[];
  remixerIn: SimpleAlbumDto[];
  inCompilation: SimpleAlbumDto[];
};

export type ArtistRole = "Main" | "Guest" | "Remixer";

export type ArtistWithRoleDto = {
  /**
   * @format uuid
   */
  id: string;
  name: string;
  role: ArtistRole;
};

export type ArtworkDto = {
  small: string;
  medium: string;
  original: string;
  colors: string[];
};

export type AudioFile = {
  /**
   * @format uuid
   */
  id: string;
  /**
   * @format date-time
   */
  createdAt: string;
  /**
   * @format date-time
   */
  updatedAt: string;
  filePath: string;
  /**
   * @format double
   */
  fileSizeInBytes: number;
  audioMetadata: AudioMetadata;
  library: MusicLibrary;
};

export type AudioMetadata = {
  /**
   * @format uuid
   */
  id: string;
  /**
   * @format date-time
   */
  createdAt: string;
  /**
   * @format date-time
   */
  updatedAt: string;
  /**
   * @format int32
   */
  bitrate: number;
  /**
   * @format int32
   */
  bitDepth?: number | null;
  /**
   * @format double
   */
  sampleRate: number;
  /**
   * @format int32
   */
  channels?: number | null;
  codec: string;
};

export type GenreDto = {
  /**
   * @format uuid
   */
  id: string;
  name: string;
};

export type MusicLibrary = {
  /**
   * @format uuid
   */
  id: string;
  /**
   * @format date-time
   */
  createdAt: string;
  /**
   * @format date-time
   */
  updatedAt: string;
  libraryPath: string;
  /**
   * @format date-time
   */
  lastScan: string;
  audioFiles: AudioFile[];
};

export type MusicLibraryDto = {
  /**
   * @format uuid
   */
  id: string;
  libraryPath: string;
  /**
   * @format date-time
   */
  lastScan: string;
};

export type OutputFormat = "AAC" | "MP3" | "Ogg" | "Opus";

export type SearchResult = {
  artists: SimpleArtistDto[];
  albums: SimpleAlbumDto[];
  tracks: TrackDto[];
};

export type SearchResultPaginatedCustomData = {
  /**
   * @format int32
   */
  availableRecords: number;
  /**
   * @format int32
   */
  totalRecords: number;
  /**
   * @format int32
   */
  resultCount: number;
  data: SearchResult;
};

export type SimpleAlbumDto = {
  /**
   * @format uuid
   */
  id: string;
  name: string;
  artists: SimpleArtistDto[];
  type?: AlbumType;
  /**
   * @format int32
   */
  releaseYear: number;
  artworks: ArtworkDto;
  /**
   * @format date-time
   */
  createdAt: string;
};

export type SimpleAlbumDtoPaginatedQuery = {
  /**
   * @format int32
   */
  availableRecords: number;
  /**
   * @format int32
   */
  totalRecords: number;
  /**
   * @format int32
   */
  resultCount: number;
  data: SimpleAlbumDto[];
};

export type SimpleArtistDto = {
  /**
   * @format uuid
   */
  id: string;
  name: string;
};

export type SimpleArtistDtoPaginatedQuery = {
  /**
   * @format int32
   */
  availableRecords: number;
  /**
   * @format int32
   */
  totalRecords: number;
  /**
   * @format int32
   */
  resultCount: number;
  data: SimpleArtistDto[];
};

export type SimpleTrackDto = {
  /**
   * @format uuid
   */
  id: string;
  title: string;
  /**
   * @format int32
   */
  durationInSeconds: number;
  /**
   * @format int32
   */
  trackNumber: number;
  /**
   * @format int32
   */
  discNumber: number;
  artists: ArtistWithRoleDto[];
  genre?: GenreDto;
};

export type StreamDto = {
  link: string;
  transcodeInfo?: TranscodeInfoDto;
  artworkUrl?: string | null;
};

export type TrackDto = {
  /**
   * @format uuid
   */
  id: string;
  title: string;
  /**
   * @format int32
   */
  durationInSeconds: number;
  comment?: string | null;
  /**
   * @format int32
   */
  trackNumber: number;
  /**
   * @format int32
   */
  discNumber: number;
  artists: ArtistWithRoleDto[];
  album: SimpleAlbumDto;
  genre?: GenreDto;
};

export type TranscodeInfoDto = {
  /**
   * @format uuid
   */
  jobId: string;
  format: OutputFormat;
  /**
   * @format int32
   */
  bitrate: number;
};
