from enum import Enum

class Error(str, Enum):
    UNKNOWN_PROCESSING_ERROR = "UNKNOWN_PROCESSING_ERROR"
    FILE_NOT_FOUND = "FILE_NOT_FOUND"
    UNPROCESSABLE_FILE = "UNPROCESSABLE_FILE"
    UNSUPPORTED_CODEC = 'UNSUPPORTED_CODEC'