# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: create-release

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - platform: win-x64
            folder_name: publish/coral-${{  github.ref_name }}-windows-x64
          - platform: linux-x64
            folder_name: publish/coral-${{  github.ref_name }}-linux-amd64
          - platform: osx-x64
            folder_name: publish/coral-${{  github.ref_name }}-macos-x64
          - platform: osx-arm64
            folder_name: publish/coral-${{  github.ref_name }}-macos-arm64
          
    steps:
      - name: Build project
        uses: GOATS2K/Coral/.github/workflows/dotnet.yml@main
      - name: Publish
        working-directory: ./src/Coral.Api
        run: |
          dotnet publish -c Release -r ${{ matrix.platform }} --self-contained -o ${{ matrix.folder_name }} -p:SkipSwaggerGen=true -p:EnableCompressionInSingleFile=true -p:Version=${{ github.ref_name }}
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: src/Coral.Api/publish/*
          tag: ${{ github.ref }}
          overwrite: false
          prerelease: true
          file_glob: true

          
        
